name: Build and Publish

on:
  push:
    branches:
      - cardinal

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        lfs: true
        fetch-depth: 0

    - name: Checkout lfs objects
      run: |
        git lfs checkout

    - name: Set variables
      run: |
        echo "PYTHON_VERSION=$(cat .python-version)" >> $GITHUB_ENV

    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pipenv
        pipenv sync

    - name: Checkout theme
      uses: actions/checkout@v2
      with:
        repository: https://github.com/mc-buckets/brutalistpelican.git
        path: theme
        lfs: true

    - name: Build and publish
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        pipenv run invoke publish